// Code generated by MockGen. DO NOT EDIT.
// Source: main.go

// Package mock_fcntllock is a generated GoMock package.
package mock_fcntllock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockReadWriteSeekCloser is a mock of ReadWriteSeekCloser interface.
type MockReadWriteSeekCloser struct {
	ctrl     *gomock.Controller
	recorder *MockReadWriteSeekCloserMockRecorder
}

// MockReadWriteSeekCloserMockRecorder is the mock recorder for MockReadWriteSeekCloser.
type MockReadWriteSeekCloserMockRecorder struct {
	mock *MockReadWriteSeekCloser
}

// NewMockReadWriteSeekCloser creates a new mock instance.
func NewMockReadWriteSeekCloser(ctrl *gomock.Controller) *MockReadWriteSeekCloser {
	mock := &MockReadWriteSeekCloser{ctrl: ctrl}
	mock.recorder = &MockReadWriteSeekCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadWriteSeekCloser) EXPECT() *MockReadWriteSeekCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockReadWriteSeekCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockReadWriteSeekCloserMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockReadWriteSeekCloser)(nil).Close))
}

// Read mocks base method.
func (m *MockReadWriteSeekCloser) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockReadWriteSeekCloserMockRecorder) Read(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReadWriteSeekCloser)(nil).Read), p)
}

// Seek mocks base method.
func (m *MockReadWriteSeekCloser) Seek(offset int64, whence int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seek", offset, whence)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seek indicates an expected call of Seek.
func (mr *MockReadWriteSeekCloserMockRecorder) Seek(offset, whence interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seek", reflect.TypeOf((*MockReadWriteSeekCloser)(nil).Seek), offset, whence)
}

// Write mocks base method.
func (m *MockReadWriteSeekCloser) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockReadWriteSeekCloserMockRecorder) Write(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockReadWriteSeekCloser)(nil).Write), p)
}
